# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a4afdea863ba49d7652dee0ff4b51eb74a8402b564ddcff515eb9ee32c5fabe675a1c50ec2998c123b12fa5cab0a7cc58c555f36a19ae6292e2a8c6efd4d787e

test:
  secret_key_base: 5842d66a26feac99c92a59ab630208e92cd44ea499233f956d05c889e4f2124f998308f9eb84a11a08b10d72abcaab8f0fc733e55bfed84839ab80bb8b245615

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
